In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
import json

In [2]:
# question1 - write a function to get the data from a file "filename" at url "url" 
#- check the contents of this file- u will see that they are names of some json file
#send a get request on each of these json files and collect the result as a list of dictionaries
#load the dict into a dataframe
# process countries data
def get_data_from_file(url, filename):
    r = requests.get(url+filename)
    filelist = r.text
    #print(filelist)
    data_list = []
    url_list = filelist.split('\n')
    #print(url_list)
    for file in url_list:
        if file =="":
            continue
        resp = requests.get(url+file)
        #either add to dict or to dataframe
        d = json.loads(resp.text)
        data_list.append(d)
    cntry_data = pd.DataFrame.from_dict(data_list)
    return cntry_data

In [3]:
# Q2- write a function to get data from the given two urls and file names
country_data = get_data_from_file("http://localhost:8082/Capitals_with_Data/", "file_list.txt")
country_capitals = get_data_from_file("http://localhost:8082/Countries_with_Capitals/", "file_list.txt")

In [4]:
# country_data = pd.read_csv('capitals_and_data.csv')
# country_capitals = pd.read_csv('country-capitals.csv')

In [5]:
country_data

,Area (sq. mi.),Birthrate,Capital City,Coastline (coast/area ratio),Deathrate,GDP ($ per capita),Infant mortality (per 1000 births),Literacy rate,Net migration,Phones (per 1000),Pop. Density (per sq. mi.),Population,Region
0,647500,"46,6",Kabul,"0,00","20,34",700.0,"163,07","36,0","23,06","3,2","48,0",31056997,ASIA (EX. NEAR EAST)
1,28748,"15,11",Tirana,"1,26","5,22",4500.0,"21,52","86,5","-4,93","71,2","124,6",3581655,EASTERN EUROPE
2,2381740,"17,14",Algiers,"0,04","4,61",6000.0,31,"70,0","-0,39","78,1","13,8",32930091,NORTHERN AFRICA
3,199,"22,46",Pago Pago,"58,29","3,27",8000.0,"9,27","97,0","-20,71","259,5","290,4",57794,OCEANIA
4,468,"8,71",Andorra la Vella,"0,00","6,25",19000.0,"4,05","100,0","6,6","497,2","152,1",71201,WESTERN EUROPE
5,1246700,"45,11",Luanda,"0,13","24,2",1900.0,"191,19","42,0",0,"7,8","9,7",12127071,SUB-SAHARAN AFRICA
6,102,"14,17",The Valley,"59,80","5,34",8600.0,"21,03","95,0","10,76","460,0","132,1",13477,LATIN AMER. & CARIB
7,2766890,"16,73",Buenos Aires,"0,18","7,55",11200.0,"15,18","97,1","0,61","220,4","14,4",39921833,LATIN AMER. & CARIB
8,29800,"12,07",Yerevan,"0,00","8,23",3500.0,"23,28","98,6","-6,47","195,7","99,9",2976372,C.W. OF IND. STATES
9,193,"11,03",Oranjestad,"35,49","6,68",28000.0,"5,89","97,0",0,"516,1","372,5",71891,LATIN AMER. & CARIB
10,7686850,"12,14",Canberra,"0,34","7,51",29000.0,"4,69","100,0","3,98","565,5","2,6",20264082,OCEANIA
11,83870,"8,74",Vienna,"0,00","9,76",30000.0,"4,66","98,0",2,"452,2","97,7",8192880,WESTERN EUROPE
12,86600,"20,74",Baku,"0,00","9,75",3400.0,"81,74","97,0","-4,9","137,1","91,9",7961619,C.W. OF IND. STATES
13,665,"17,8",Manama,"24,21","4,14",16900.0,"17,27","89,1","1,05","281,3","1050,5",698585,NEAR EAST
14,144000,"29,8",Dhaka,"0,40","8,27",1900.0,"62,6","43,1","-0,71","7,3","1023,4",147365352,ASIA (EX. NEAR EAST)
15,431,"12,71",Bridgetown,"22,51","8,67",15700.0,"12,5","97,4","-0,31","481,9","649,5",279912,LATIN AMER. & CARIB
16,207600,"11,16",Minsk,"0,00","14,02",6100.0,"13,37","99,6","2,54","319,1","49,6",10293011,C.W. OF IND. STATES
17,30528,"10,38",Brussels,"0,22","10,27",29100.0,"4,68","98,0","1,23","462,6","340,0",10379067,WESTERN EUROPE
18,22966,"28,84",Belmopan,"1,68","5,72",4900.0,"25,69","94,1",0,"115,7","12,5",287730,LATIN AMER. & CARIB
19,112620,"38,85",Porto-Novo,"0,11","12,22",1100.0,85,"40,9",0,"9,7","69,8",7862944,SUB-SAHARAN AFRICA
20,53,"11,4",Hamilton,"194,34","7,74",36000.0,"8,53","98,0","2,49","851,4","1241,0",65773,NORTHERN AMERICA
21,47000,"33,65",Thimphu,"0,00","12,7",1300.0,"100,44","42,2",0,"14,3","48,5",2279723,ASIA (EX. NEAR EAST)
22,1098580,"23,3",La Paz,"0,00","7,53",2400.0,"53,11","87,2","-1,32","71,9","8,2",8989046,LATIN AMER. & CARIB
23,600370,"23,08",Gaborone,"0,00","29,5",9000.0,"54,58","79,8",0,"80,5","2,7",1639833,SUB-SAHARAN AFRICA
24,8511965,"16,56",Brasilia,"0,09","6,17",7600.0,"29,61","86,4","-0,03","225,3","22,1",188078227,LATIN AMER. & CARIB
25,110910,"9,65",Sofia,"0,32","14,27",7600.0,"20,55","98,6","-4,58","336,3","66,6",7385367,EASTERN EUROPE
26,274200,"45,62",Ouagadougou,"0,00","15,6",1100.0,"97,57","26,6",0,"7,0","50,7",13902972,SUB-SAHARAN AFRICA
27,27830,"42,22",Bujumbura,"0,00","13,46",600.0,"69,29","51,6","-0,06","3,4","290,7",8090068,SUB-SAHARAN AFRICA
28,181040,"26,9",Phnom Penh,"0,24","9,06",1900.0,"71,48","69,4",0,"2,6","76,7",13881427,ASIA (EX. NEAR EAST)
29,475440,"33,89",Yaounde,"0,08","13,47",1800.0,"68,26","79,0",0,"5,7","36,5",17340702,SUB-SAHARAN AFRICA
...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,98480,10,Seoul,"2,45","5,85",17800,"7,05","97,9",0,"486,1","496,0",48846823,ASIA (EX. NEAR EAST)
151,65610,"15,51",Colombo,"2,04","6,52",3700.0,"14,35","92,3","-1,31","61,5","308,2",20222240,ASIA (EX. NEAR EAST)
152,2505810,"34,53",Khartoum,"0,03","8,97",1900.0,"62,5","61,1","-0,02","16,3","16,5",41236378,SUB-SAHARAN AFRICA
153,163270,"18,02",Paramaribo,"0,24","7,27",4000.0,"23,57","93,0","-8,81","184,7","2,7",439117,LATIN AMER. & CARIB
154,17363,"27,41",Mbabane,"0,00","29,74",4900.0,"69,27","81,6",0,"30,8","65,5",1136334,SUB-SAHARAN AFRICA
155,449964,"10,27",Stockholm,"0,72","10,31",26800.0,"2,77","99,0","1,67","715,0","20,0",9016596,WESTERN EUROPE
156,41290,"9,71",Bern,"0,00","8,49",32700.0,"4,39","99,0","4,05","680,9","182,2",7523934,WESTERN EUROPE
157,185180,"27,76",Damascus,"0,10","4,81",3300.0,"29,53","76,9",0,"153,8","102,0",18881361,NEAR EAST
158,35980,"12,56",Taipei,"4,35","6,48",23400.0,"6,4","96,1",0,"591,0","640,3",23036087,ASIA (EX. NEAR EAST)
159,143100,"32,65",Dushanbe,"0,00","8,25",1000.0,"110,76","99,4","-2,86","33,5","51,2",7320815,C.W. OF IND. STATES
160,945087,"37,71",Dar es Salaam,"0,15","16,39",600.0,"98,54","78,2","-2,06","4,0","39,6",37445392,SUB-SAHARAN AFRICA
161,514000,"13,87",Bangkok,"0,63","7,04",7400.0,"20,48","92,6",0,"108,9","125,7",64631595,ASIA (EX. NEAR EAST)
162,56785,"37,01",Lome,"0,10","9,83",1500.0,"66,61","60,9",0,"10,6","97,7",5548702,SUB-SAHARAN AFRICA
163,748,"25,37",Nuku'alofa,"56,02","5,28",2200.0,"12,62","98,5",0,"97,7","153,3",114689,OCEANIA
164,163610,"15,52",Tunis,"0,70","5,13",6900.0,"24,77","74,2","-0,57","123,6","62,2",10175014,NORTHERN AFRICA
165,780580,"16,62",Ankara,"0,92","5,97",6700.0,"41,04","86,5",0,"269,5","90,2",70413958,NEAR EAST
166,488100,"27,61",Ashgabat,"0,00","8,6",5800.0,"73,08","98,0","-0,86","74,6","10,3",5042920,C.W. OF IND. STATES
167,236040,"47,35",Kampala,"0,00","12,24",1400.0,"67,83","69,9",0,"3,6","119,5",28195754,SUB-SAHARAN AFRICA
168,603700,"8,82",Kyiv,"0,46","14,39",5400.0,"20,34","99,7","-0,39","259,9","77,4",46710816,C.W. OF IND. STATES
169,82880,"18,96",Abu Dhabi,"1,59","4,4",23200.0,"14,51","77,9","1,03","475,3","31,4",2602713,NEAR EAST
170,244820,"10,71",London,"5,08","10,13",27700.0,"5,16","99,0","2,19","543,5","247,6",60609153,WESTERN EUROPE
171,9631420,"14,14",Washington D.C.,"0,21","8,26",37800.0,"6,5","97,0","3,41","898,0","31,0",298444215,NORTHERN AMERICA
172,176220,"13,91",Montevideo,"0,37","9,05",12800.0,"11,95","98,0","-0,32","291,4","19,5",3431932,LATIN AMER. & CARIB
173,447400,"26,36",Tashkent,"0,00","7,84",1700.0,"71,1","99,3","-1,72","62,9","61,0",27307134,C.W. OF IND. STATES
174,12200,"22,72",Port-Vila,"20,72","7,82",2900.0,"55,16","53,0",0,"32,6","17,1",208869,OCEANIA
175,912050,"18,71",Caracas,"0,31","4,92",4800.0,"22,2","93,4","-0,04","140,1","28,2",25730435,LATIN AMER. & CARIB
176,329560,"16,86",Hanoi,"1,05","6,22",2500.0,"25,95","90,3","-0,45","187,7","256,1",84402966,ASIA (EX. NEAR EAST)
177,527970,"42,89",Sanaa,"0,36","8,3",800.0,"61,5","50,2",0,"37,2","40,6",21456188,NEAR EAST
178,752614,41,Lusaka,"0,00","19,93",800.0,"88,29","80,6",0,"8,2","15,3",11502010,SUB-SAHARAN AFRICA
179,390580,"28,01",Harare,"0,00","21,84",1900.0,"67,69","90,7",0,"26,8","31,3",12236805,SUB-SAHARAN AFRICA

In [6]:
country_capitals

,Capital,Capital Latitude,Captial Longitude,Continent,Country
0,Hargeisa,9.55,44.05,Africa,Somaliland
1,King Edward Point,-54.283333,-36.5,Antarctica,South Georgia and South Sandwich Islands
2,Port-aux-Français,-49.35,70.216667,Antarctica,French Southern and Antarctic Lands
3,Mariehamn,60.11666700000001,19.9,Europe,Aland Islands
4,Yaren,-0.5477,166.920867,Australia,Nauru
5,Marigot,18.0731,-63.0822,North America,Saint Martin
6,Atafu,-9.166667,-171.833333,Australia,Tokelau
7,El-Aaiún,27.153610999999998,-13.203332999999999,Africa,Western Sahara
8,Kabul,34.516666666666666,69.18333299999999,Asia,Afghanistan
9,Tirana,41.31666666666667,19.816667000000002,Europe,Albania
10,Algiers,36.75,3.05,Africa,Algeria
11,Pago Pago,-14.266666666666667,-170.7,Australia,American Samoa
12,Andorra la Vella,42.5,1.516667,Europe,Andorra
13,Luanda,-8.833333333333334,13.216667000000001,Africa,Angola
14,The Valley,18.216666666666665,-63.05,North America,Anguilla
15,Saint John's,17.116666666666667,-61.85,North America,Antigua and Barbuda
16,Buenos Aires,-34.583333333333336,-58.666667000000004,South America,Argentina
17,Yerevan,40.16666666666666,44.5,Europe,Armenia
18,Oranjestad,12.516666666666667,-70.033333,North America,Aruba
19,Canberra,-35.266666666666666,149.133333,Australia,Australia
20,Vienna,48.2,16.366667,Europe,Austria
21,Baku,40.38333333333333,49.866667,Europe,Azerbaijan
22,Nassau,25.08333333333333,-77.35,North America,Bahamas
23,Manama,26.23333333333333,50.566666999999995,Asia,Bahrain
24,Dhaka,23.716666666666665,90.4,Asia,Bangladesh
25,Bridgetown,13.1,-59.61666700000001,North America,Barbados
26,Minsk,53.9,27.566667,Europe,Belarus
27,Brussels,50.83333333333334,4.3333330000000005,Europe,Belgium
28,Belmopan,17.25,-88.766667,Central America,Belize
29,Porto-Novo,6.4833333333333325,2.6166669999999996,Africa,Benin
...,...,...,...,...,...
208,Taipei,25.03333333333333,121.516667,Asia,Taiwan
209,Dushanbe,38.55,68.766667,Asia,Tajikistan
210,Dar es Salaam,-6.8,39.283333,Africa,Tanzania
211,Bangkok,13.75,100.516667,Asia,Thailand
212,Dili,-8.583333333333334,125.6,Asia,Timor-Leste
213,Lome,6.116666666666666,1.216667,Africa,Togo
214,Nuku'alofa,-21.133333333333333,-175.2,Australia,Tonga
215,Port of Spain,10.65,-61.516667000000005,North America,Trinidad and Tobago
216,Tunis,36.8,10.183333,Africa,Tunisia
217,Ankara,39.93333333333333,32.866667,Europe,Turkey
218,Ashgabat,37.95,58.38333299999999,Asia,Turkmenistan
219,Grand Turk,21.466666666666665,-71.133333,North America,Turks and Caicos Islands
220,Funafuti,-8.516666666666667,179.216667,Australia,Tuvalu
221,Kampala,0.31666666666666665,32.55,Africa,Uganda
222,Kyiv,50.43333333333333,30.516666999999998,Europe,Ukraine
223,Abu Dhabi,24.466666666666665,54.36666700000001,Asia,United Arab Emirates
224,London,51.5,-0.083333,Europe,United Kingdom
225,Washington D.C.,38.883333,-77.0,Central America,United States
226,Montevideo,-34.85,-56.166667000000004,South America,Uruguay
227,Tashkent,41.31666666666667,69.25,Asia,Uzbekistan
228,Port-Vila,-17.733333333333334,168.316667,Australia,Vanuatu
229,Caracas,10.483333333333333,-66.866667,South America,Venezuela
230,Hanoi,21.03333333333333,105.85,Asia,Vietnam
231,Charlotte Amalie,18.35,-64.93333299999999,North America,US Virgin Islands
232,Mata-Utu,-13.95,-171.933333,Australia,Wallis and Futuna
233,Sanaa,15.35,44.2,Asia,Yemen
234,Lusaka,-15.416666666666664,28.283333000000002,Africa,Zambia
235,Harare,-17.816666666666666,31.033333000000002,Africa,Zimbabwe
236,North Nicosia,35.183333000000005,33.366667,Europe,Northern Cyprus
237,Diego Garcia,-7.3,72.4,Africa,British Indian Ocean Territory

In [13]:
# Q-3 Write a function to clean the 2 dataframes
# Rename column - "Captial Longitude" to "Capital Longitude"
# delete the region column
country_capitals.rename(columns={'Captial Longitude':'Capital Longitude'}, inplace=True)
country_data = country_data.drop(columns=['Region','Phones (per 1000)' ])

In [17]:
#Also many columns contains commas (,) instead of (.) decimal points- fix so that the data is a a valid decimal number
country_data['Literacy rate'] = country_data['Literacy rate'].str.replace(',', '.')
#lit = [float((k).replace(',','.')) for k in list(country_data['Literacy rate'])]
country_data['Birthrate'] = country_data['Birthrate'].str.replace(',', '.')
country_data['Deathrate'] = country_data['Deathrate'].str.replace(',', '.')
country_data['Coastline (coast/area ratio)'] = country_data['Coastline (coast/area ratio)'].str.replace(',', '.')
country_data['Infant mortality (per 1000 births)'] = country_data['Infant mortality (per 1000 births)'].str.replace(',', '.')
country_data

,Area (sq. mi.),Birthrate,Capital,Coastline (coast/area ratio),Deathrate,GDP ($ per capita),Infant mortality (per 1000 births),Literacy rate,Net migration,Pop. Density (per sq. mi.),Population
0,647500,46.6,Kabul,0.00,20.34,700.0,163.07,36.0,"23,06","48,0",31056997
1,28748,15.11,Tirana,1.26,5.22,4500.0,21.52,86.5,"-4,93","124,6",3581655
2,2381740,17.14,Algiers,0.04,4.61,6000.0,31,70.0,"-0,39","13,8",32930091
3,199,22.46,Pago Pago,58.29,3.27,8000.0,9.27,97.0,"-20,71","290,4",57794
4,468,8.71,Andorra la Vella,0.00,6.25,19000.0,4.05,100.0,"6,6","152,1",71201
5,1246700,45.11,Luanda,0.13,24.2,1900.0,191.19,42.0,0,"9,7",12127071
6,102,14.17,The Valley,59.80,5.34,8600.0,21.03,95.0,"10,76","132,1",13477
7,2766890,16.73,Buenos Aires,0.18,7.55,11200.0,15.18,97.1,"0,61","14,4",39921833
8,29800,12.07,Yerevan,0.00,8.23,3500.0,23.28,98.6,"-6,47","99,9",2976372
9,193,11.03,Oranjestad,35.49,6.68,28000.0,5.89,97.0,0,"372,5",71891
10,7686850,12.14,Canberra,0.34,7.51,29000.0,4.69,100.0,"3,98","2,6",20264082
11,83870,8.74,Vienna,0.00,9.76,30000.0,4.66,98.0,2,"97,7",8192880
12,86600,20.74,Baku,0.00,9.75,3400.0,81.74,97.0,"-4,9","91,9",7961619
13,665,17.8,Manama,24.21,4.14,16900.0,17.27,89.1,"1,05","1050,5",698585
14,144000,29.8,Dhaka,0.40,8.27,1900.0,62.6,43.1,"-0,71","1023,4",147365352
15,431,12.71,Bridgetown,22.51,8.67,15700.0,12.5,97.4,"-0,31","649,5",279912
16,207600,11.16,Minsk,0.00,14.02,6100.0,13.37,99.6,"2,54","49,6",10293011
17,30528,10.38,Brussels,0.22,10.27,29100.0,4.68,98.0,"1,23","340,0",10379067
18,22966,28.84,Belmopan,1.68,5.72,4900.0,25.69,94.1,0,"12,5",287730
19,112620,38.85,Porto-Novo,0.11,12.22,1100.0,85,40.9,0,"69,8",7862944
20,53,11.4,Hamilton,194.34,7.74,36000.0,8.53,98.0,"2,49","1241,0",65773
21,47000,33.65,Thimphu,0.00,12.7,1300.0,100.44,42.2,0,"48,5",2279723
22,1098580,23.3,La Paz,0.00,7.53,2400.0,53.11,87.2,"-1,32","8,2",8989046
23,600370,23.08,Gaborone,0.00,29.5,9000.0,54.58,79.8,0,"2,7",1639833
24,8511965,16.56,Brasilia,0.09,6.17,7600.0,29.61,86.4,"-0,03","22,1",188078227
25,110910,9.65,Sofia,0.32,14.27,7600.0,20.55,98.6,"-4,58","66,6",7385367
26,274200,45.62,Ouagadougou,0.00,15.6,1100.0,97.57,26.6,0,"50,7",13902972
27,27830,42.22,Bujumbura,0.00,13.46,600.0,69.29,51.6,"-0,06","290,7",8090068
28,181040,26.9,Phnom Penh,0.24,9.06,1900.0,71.48,69.4,0,"76,7",13881427
29,475440,33.89,Yaounde,0.08,13.47,1800.0,68.26,79.0,0,"36,5",17340702
...,...,...,...,...,...,...,...,...,...,...,...
150,98480,10,Seoul,2.45,5.85,17800,7.05,97.9,0,"496,0",48846823
151,65610,15.51,Colombo,2.04,6.52,3700.0,14.35,92.3,"-1,31","308,2",20222240
152,2505810,34.53,Khartoum,0.03,8.97,1900.0,62.5,61.1,"-0,02","16,5",41236378
153,163270,18.02,Paramaribo,0.24,7.27,4000.0,23.57,93.0,"-8,81","2,7",439117
154,17363,27.41,Mbabane,0.00,29.74,4900.0,69.27,81.6,0,"65,5",1136334
155,449964,10.27,Stockholm,0.72,10.31,26800.0,2.77,99.0,"1,67","20,0",9016596
156,41290,9.71,Bern,0.00,8.49,32700.0,4.39,99.0,"4,05","182,2",7523934
157,185180,27.76,Damascus,0.10,4.81,3300.0,29.53,76.9,0,"102,0",18881361
158,35980,12.56,Taipei,4.35,6.48,23400.0,6.4,96.1,0,"640,3",23036087
159,143100,32.65,Dushanbe,0.00,8.25,1000.0,110.76,99.4,"-2,86","51,2",7320815
160,945087,37.71,Dar es Salaam,0.15,16.39,600.0,98.54,78.2,"-2,06","39,6",37445392
161,514000,13.87,Bangkok,0.63,7.04,7400.0,20.48,92.6,0,"125,7",64631595
162,56785,37.01,Lome,0.10,9.83,1500.0,66.61,60.9,0,"97,7",5548702
163,748,25.37,Nuku'alofa,56.02,5.28,2200.0,12.62,98.5,0,"153,3",114689
164,163610,15.52,Tunis,0.70,5.13,6900.0,24.77,74.2,"-0,57","62,2",10175014
165,780580,16.62,Ankara,0.92,5.97,6700.0,41.04,86.5,0,"90,2",70413958
166,488100,27.61,Ashgabat,0.00,8.6,5800.0,73.08,98.0,"-0,86","10,3",5042920
167,236040,47.35,Kampala,0.00,12.24,1400.0,67.83,69.9,0,"119,5",28195754
168,603700,8.82,Kyiv,0.46,14.39,5400.0,20.34,99.7,"-0,39","77,4",46710816
169,82880,18.96,Abu Dhabi,1.59,4.4,23200.0,14.51,77.9,"1,03","31,4",2602713
170,244820,10.71,London,5.08,10.13,27700.0,5.16,99.0,"2,19","247,6",60609153
171,9631420,14.14,Washington D.C.,0.21,8.26,37800.0,6.5,97.0,"3,41","31,0",298444215
172,176220,13.91,Montevideo,0.37,9.05,12800.0,11.95,98.0,"-0,32","19,5",3431932
173,447400,26.36,Tashkent,0.00,7.84,1700.0,71.1,99.3,"-1,72","61,0",27307134
174,12200,22.72,Port-Vila,20.72,7.82,2900.0,55.16,53.0,0,"17,1",208869
175,912050,18.71,Caracas,0.31,4.92,4800.0,22.2,93.4,"-0,04","28,2",25730435
176,329560,16.86,Hanoi,1.05,6.22,2500.0,25.95,90.3,"-0,45","256,1",84402966
177,527970,42.89,Sanaa,0.36,8.3,800.0,61.5,50.2,0,"40,6",21456188
178,752614,41,Lusaka,0.00,19.93,800.0,88.29,80.6,0,"15,3",11502010
179,390580,28.01,Harare,0.00,21.84,1900.0,67.69,90.7,0,"31,3",12236805

In [26]:
# Convert all numerical columns to float except population
country_data = country_data.astype({"Area (sq. mi.)": float,
                                    "Birthrate": float, "Coastline (coast/area ratio)": float, "Deathrate":float,
                                    "GDP ($ per capita)":float, "Infant mortality (per 1000 births)": float,
                                    "Literacy rate": float, "Population":int})
country_capitals = country_capitals.astype({"Capital Latitude":float,"Capital Longitude":float})



## merge the two datasets using pandas
* needs renaming Capital City column to Capital

In [4]:
#Q-4 merge the two dataframes based on the name of the capital in both datasets
country_data.rename(columns={'Capital City':'Capital'}, inplace=True)
result = pd.merge(country_capitals, country_data, on='Capital', how='inner', validate=None)
result

NameError: name 'country_data' is not defined

In [3]:
#Q-5 output all rows whose population is < threshold or output names of all countries as a list whose pop is less than 10000

a = result[result.Population< 100000]
a

NameError: name 'result' is not defined


## find properties in the data using Pandas
* mean and standard deviation of literacy
* correlation coefficient between GDP and literacy

In [29]:
#Q-6 find the mean, std dev of literacy across all countries
#statistical properties of data- mean and std dev
lit = result['Literacy rate']

In [30]:
m = lit.mean()
s = lit.std()

20.17855764673653

In [31]:
gdp  = result['GDP ($ per capita)']

In [32]:
#Q-7 find the correlation coefficient between gdp and literacy across all countries
c = gdp.corr(lit)
c

0.5162204543369631

Plotting
* Plot histogram of GDP
* Plot histogram of literacy
* scatter plot of literacy vs GDP

In [ ]:
plt.hist(result['GDP ($ per capita)'],  edgecolor ='w')
plt.show()

In [ ]:
plt.hist(lit, color = 'b', edgecolor ='w')
plt.show()

In [ ]:
plt.scatter(lit, gdp)
plt.xlabel('Literacy rate')
plt.ylabel('GDP')
plt.show()